const biddingSites = [
  {
    "name": "中国国际招标网",
    "url": "https://www.chinabidding.com.cn",
    "source_level": "国家级",
    "province": "全国",
    "city": "全国",
    "platform_type": "官方核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "机电产品国际招标（商务部指定）"
  },
  {
    "name": "中国招标投标公共服务平台",
    "url": "https://www.cebpubservice.com",
    "source_level": "国家级",
    "province": "全国",
    "city": "全国",
    "platform_type": "官方核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "全国依法必招项目（工程 / 货物 / 服务）"
  },
  {
    "name": "中国政府采购网",
    "url": "https://www.ccgp.gov.cn",
    "source_level": "国家级",
    "province": "全国",
    "city": "全国",
    "platform_type": "官方核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "各级政府 / 事业单位政府采购（含中小企业预留）"
  },
  {
    "name": "中央政府采购网",
    "url": "https://www.zycg.gov.cn",
    "source_level": "国家级",
    "province": "全国",
    "city": "全国",
    "platform_type": "官方核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "中央单位政府采购项目"
  },
  {
    "name": "全国公共资源交易平台",
    "url": "https://www.ggzy.gov.cn",
    "source_level": "国家级",
    "province": "全国",
    "city": "全国",
    "platform_type": "官方核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "工程 / 土地 / 产权 / 政府采购等 10 大类（31 省近 400 个子平台）"
  },
  {
    "name": "军队采购网",
    "url": "https://www.plap.cn",
    "source_level": "国家级",
    "province": "全国",
    "city": "全国",
    "platform_type": "官方核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "军队系统采购信息"
  },
  {
    "name": "上海市公共资源交易中心",
    "url": "https://www.shggzy.com",
    "source_level": "地方省市",
    "province": "上海",
    "city": "上海",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "上海全市公共资源交易项目"
  },
  {
    "name": "上海市政府采购网",
    "url": "http://www.zfcg.sh.gov.cn",
    "source_level": "地方省市",
    "province": "上海",
    "city": "上海",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "上海全市政府采购项目"
  },
  {
    "name": "云南省公共资源交易信息网",
    "url": "http://ggzy.yn.gov.cn",
    "source_level": "地方省市",
    "province": "云南",
    "city": "昆明",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "云南全省公共资源交易项目"
  },
  {
    "name": "云南省政府采购网",
    "url": "http://www.ccgp-yunnan.gov.cn",
    "source_level": "地方省市",
    "province": "云南",
    "city": "昆明",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "云南全省政府采购项目"
  },
  {
    "name": "兵团公共资源交易平台",
    "url": "https://ggzy.xjbt.gov.cn",
    "source_level": "地方省市",
    "province": "兵团",
    "city": "兵团",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "新疆生产建设兵团公共资源交易项目"
  },
  {
    "name": "兵团政府采购网",
    "url": "http://ccgp-bingtuan.gov.cn",
    "source_level": "地方省市",
    "province": "兵团",
    "city": "兵团",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "新疆生产建设兵团政府采购项目"
  },
  {
    "name": "内蒙古招标投标公共服务平台",
    "url": "https://zbgg.nmgztb.com.cn",
    "source_level": "地方省市",
    "province": "内蒙古",
    "city": "呼和浩特",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "内蒙古全区招投标项目"
  },
  {
    "name": "内蒙古自治区政府采购网",
    "url": "http://www.ccgp-neimenggu.gov.cn",
    "source_level": "地方省市",
    "province": "内蒙古",
    "city": "呼和浩特",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "内蒙古全区政府采购项目"
  },
  {
    "name": "北京市公共资源交易服务平台",
    "url": "https://ggzyfw.beijing.gov.cn",
    "source_level": "地方省市",
    "province": "北京",
    "city": "北京",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "北京全市工程 / 采购 / 土地等交易项目"
  },
  {
    "name": "北京市政府采购网",
    "url": "http://www.ccgp-beijing.gov.cn",
    "source_level": "地方省市",
    "province": "北京",
    "city": "北京",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "北京本级及区县政府采购项目"
  },
  {
    "name": "吉林省公共资源交易公共服务平台",
    "url": "http://www.jl.gov.cn",
    "source_level": "地方省市",
    "province": "吉林",
    "city": "长春",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "吉林全省招投标项目"
  },
  {
    "name": "吉林省政府采购网",
    "url": "http://www.ccgp-jilin.gov.cn",
    "source_level": "地方省市",
    "province": "吉林",
    "city": "长春",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "吉林全省政府采购项目"
  },
  {
    "name": "全国公共资源交易平台（四川省）",
    "url": "http://www.scggzy.gov.cn",
    "source_level": "地方省市",
    "province": "四川",
    "city": "成都",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "四川全省公共资源交易项目"
  },
  {
    "name": "四川政府采购",
    "url": "http://www.ccgp-sichuan.gov.cn",
    "source_level": "地方省市",
    "province": "四川",
    "city": "成都",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "四川全省政府采购项目"
  },
  {
    "name": "天津市公共资源交易平台",
    "url": "http://ggzy.zwfwb.tj.gov.cn",
    "source_level": "地方省市",
    "province": "天津",
    "city": "天津",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "天津全市公共资源交易项目"
  },
  {
    "name": "天津市政府采购网",
    "url": "http://www.ccgp-tianjin.gov.cn",
    "source_level": "地方省市",
    "province": "天津",
    "city": "天津",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "天津本级及区县政府采购项目"
  },
  {
    "name": "宁夏回族自治区公共资源交易网",
    "url": "http://www.nxggzyjy.org",
    "source_level": "地方省市",
    "province": "宁夏",
    "city": "银川",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "宁夏全区公共资源交易项目"
  },
  {
    "name": "宁夏回族自治区政府采购网",
    "url": "http://www.ccgp-ningxia.gov.cn",
    "source_level": "地方省市",
    "province": "宁夏",
    "city": "银川",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "宁夏全区政府采购项目"
  },
  {
    "name": "安徽省公共资源交易监管网",
    "url": "http://ggzy.ah.gov.cn",
    "source_level": "地方省市",
    "province": "安徽",
    "city": "合肥",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "安徽全省公共资源交易项目"
  },
  {
    "name": "安徽省政府采购网",
    "url": "http://www.ccgp-anhui.gov.cn",
    "source_level": "地方省市",
    "province": "安徽",
    "city": "合肥",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "安徽全省政府采购项目"
  },
  {
    "name": "山东省公共资源交易平台",
    "url": "https://ggzyjy.shandong.gov.cn",
    "source_level": "地方省市",
    "province": "山东",
    "city": "济南",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "山东全省公共资源交易项目"
  },
  {
    "name": "山东省政府采购网",
    "url": "http://www.ccgp-shandong.gov.cn",
    "source_level": "地方省市",
    "province": "山东",
    "city": "济南",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "山东全省政府采购项目"
  },
  {
    "name": "山西政府采购网",
    "url": "http://www.ccgp-shanxi.gov.cn",
    "source_level": "地方省市",
    "province": "山西",
    "city": "太原",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "山西全省政府采购项目"
  },
  {
    "name": "山西省招标投标公共服务平台",
    "url": "http://www.sxbid.com.cn",
    "source_level": "地方省市",
    "province": "山西",
    "city": "太原",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "山西全省招投标项目"
  },
  {
    "name": "广东省公共资源交易平台",
    "url": "http://bs.gdggzy.org.cn/osh-web",
    "source_level": "地方省市",
    "province": "广东",
    "city": "广州",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "广东全省公共资源交易项目"
  },
  {
    "name": "广东省政府采购网",
    "url": "https://gdgpo.czt.gd.gov.cn",
    "source_level": "地方省市",
    "province": "广东",
    "city": "广州",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "广东全省政府采购项目"
  },
  {
    "name": "深圳公共资源交易网",
    "url": "https://ww.szggzy.com",
    "source_level": "地方省市",
    "province": "广东",
    "city": "深圳",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "深圳全市公共资源交易项目"
  },
  {
    "name": "深圳政府采购网",
    "url": "http://zfcg.sz.gov.cn",
    "source_level": "地方省市",
    "province": "广东",
    "city": "深圳",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "深圳全市政府采购项目"
  },
  {
    "name": "广西壮族自治区公共资源交易中心",
    "url": "http://ggzyjy.gxzf.gov.cn",
    "source_level": "地方省市",
    "province": "广西",
    "city": "南宁",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "广西全区公共资源交易项目"
  },
  {
    "name": "广西政府采购网",
    "url": "http://www.ccgp-guangxi.gov.cn",
    "source_level": "地方省市",
    "province": "广西",
    "city": "南宁",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "广西全区政府采购项目"
  },
  {
    "name": "新疆公共资源交易网",
    "url": "https://ggzy.xinjiang.gov.cn",
    "source_level": "地方省市",
    "province": "新疆",
    "city": "乌鲁木齐",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "新疆全区公共资源交易项目"
  },
  {
    "name": "新疆政府采购网",
    "url": "http://www.ccgp-xinjiang.gov.cn",
    "source_level": "地方省市",
    "province": "新疆",
    "city": "乌鲁木齐",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "新疆全区政府采购项目"
  },
  {
    "name": "江苏政府采购网",
    "url": "http://www.ccgp-jiangsu.gov.cn",
    "source_level": "地方省市",
    "province": "江苏",
    "city": "南京",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "江苏全省政府采购项目"
  },
  {
    "name": "江苏省招标投标公共服务平台",
    "url": "http://www.jszbtb.com",
    "source_level": "地方省市",
    "province": "江苏",
    "city": "南京",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "江苏全省招投标项目"
  },
  {
    "name": "江西省公共资源交易平台",
    "url": "http://www.jxsggzy.cn/web",
    "source_level": "地方省市",
    "province": "江西",
    "city": "南昌",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "江西全省公共资源交易项目"
  },
  {
    "name": "江西省政府采购网",
    "url": "http://www.ccgp-jiangxi.gov.cn/web",
    "source_level": "地方省市",
    "province": "江西",
    "city": "南昌",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "江西全省政府采购项目"
  },
  {
    "name": "中国河北政府采购网",
    "url": "https://www.ccgp-hebei.gov.cn/province",
    "source_level": "地方省市",
    "province": "河北",
    "city": "石家庄",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "河北全省政府采购项目"
  },
  {
    "name": "河北省公共资源交易服务平台",
    "url": "https://szj.hebei.gov.cn/hbggfwpt",
    "source_level": "地方省市",
    "province": "河北",
    "city": "石家庄",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "河北全省工程 / 采购等交易项目"
  },
  {
    "name": "河南省公共资源交易中心",
    "url": "http://hnsggzyjy.henan.gov.cn",
    "source_level": "地方省市",
    "province": "河南",
    "city": "郑州",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "河南全省公共资源交易项目"
  },
  {
    "name": "河南省政府采购网",
    "url": "http://www.ccgp-henan.gov.cn",
    "source_level": "地方省市",
    "province": "河南",
    "city": "郑州",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "河南全省政府采购项目"
  },
  {
    "name": "浙江招标投标公共服务平台",
    "url": "https://zj.bidnews.cn",
    "source_level": "地方省市",
    "province": "浙江",
    "city": "杭州",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "浙江全省招投标项目"
  },
  {
    "name": "浙江政府采购网",
    "url": "http://www.ccgp-zhejiang.gov.cn",
    "source_level": "地方省市",
    "province": "浙江",
    "city": "杭州",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "浙江全省政府采购项目"
  },
  {
    "name": "中国海南政府采购网",
    "url": "http://www.ccgp-hainan.gov.cn",
    "source_level": "地方省市",
    "province": "海南",
    "city": "海口",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "海南全省政府采购项目"
  },
  {
    "name": "海南省公共资源交易服务平台",
    "url": "http://ggzy.hainan.gov.cn",
    "source_level": "地方省市",
    "province": "海南",
    "city": "海口",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "海南全省公共资源交易项目"
  },
  {
    "name": "湖北省公共资源交易电子服务系统",
    "url": "https://www.hbggzy.gov.cn",
    "source_level": "地方省市",
    "province": "湖北",
    "city": "武汉",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "湖北全省公共资源交易项目"
  },
  {
    "name": "湖北省政府购买服务信息平台",
    "url": "http://www.ccgp-hubei.gov.cn",
    "source_level": "地方省市",
    "province": "湖北",
    "city": "武汉",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "湖北全省政府采购项目"
  },
  {
    "name": "中国湖南政府采购网",
    "url": "http://www.ccgp-hunan.gov.cn",
    "source_level": "地方省市",
    "province": "湖南",
    "city": "长沙",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "湖南全省政府采购项目"
  },
  {
    "name": "湖南省公共资源交易平台",
    "url": "https://www.hnsggzy.com",
    "source_level": "地方省市",
    "province": "湖南",
    "city": "长沙",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "湖南全省公共资源交易项目"
  },
  {
    "name": "甘肃政府采购网",
    "url": "http://www.ccgp-gansu.gov.cn",
    "source_level": "地方省市",
    "province": "甘肃",
    "city": "兰州",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "甘肃全省政府采购项目"
  },
  {
    "name": "甘肃省公共资源交易网",
    "url": "http://ggzyjy.gansu.gov.cn",
    "source_level": "地方省市",
    "province": "甘肃",
    "city": "兰州",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "甘肃全省公共资源交易项目"
  },
  {
    "name": "福建省公共资源交易电子公共服务平台",
    "url": "https://ggzyfw.fujian.gov.cn",
    "source_level": "地方省市",
    "province": "福建",
    "city": "福州",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "福建全省公共资源交易项目"
  },
  {
    "name": "福建省政府采购网",
    "url": "http://www.ccgp-fujian.gov.cn",
    "source_level": "地方省市",
    "province": "福建",
    "city": "福州",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "福建全省政府采购项目"
  },
  {
    "name": "西藏自治区公共资源交易信息网",
    "url": "http://xzggzy.gov.cn:9090",
    "source_level": "地方省市",
    "province": "西藏",
    "city": "拉萨",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "西藏全区公共资源交易项目"
  },
  {
    "name": "西藏自治区政府采购网",
    "url": "http://www.ccgp-xizang.gov.cn",
    "source_level": "地方省市",
    "province": "西藏",
    "city": "拉萨",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "西藏全区政府采购项目"
  },
  {
    "name": "贵州省公共资源交易公共服务平台",
    "url": "http://ggzy.guizhou.gov.cn",
    "source_level": "地方省市",
    "province": "贵州",
    "city": "贵阳",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "贵州全省公共资源交易项目"
  },
  {
    "name": "贵州省政府采购网",
    "url": "https://gzgp.zbytb.com",
    "source_level": "地方省市",
    "province": "贵州",
    "city": "贵阳",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "贵州全省政府采购项目"
  },
  {
    "name": "大连市公共资源交易中心",
    "url": "http://ggzyjy.dl.gov.cn/tpfront",
    "source_level": "地方省市",
    "province": "辽宁",
    "city": "大连",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "大连全市公共资源交易项目"
  },
  {
    "name": "大连市政府采购网",
    "url": "http://www.ccgp-dalian.gov.cn",
    "source_level": "地方省市",
    "province": "辽宁",
    "city": "大连",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "大连全市政府采购项目"
  },
  {
    "name": "辽宁政府采购网",
    "url": "http://www.ccgp-liaoning.gov.cn/portalindex",
    "source_level": "地方省市",
    "province": "辽宁",
    "city": "沈阳",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "辽宁全省政府采购项目"
  },
  {
    "name": "辽宁省公共资源交易网",
    "url": "https://ggzy.ln.gov.cn",
    "source_level": "地方省市",
    "province": "辽宁",
    "city": "沈阳",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "辽宁全省公共资源交易项目"
  },
  {
    "name": "重庆市公共资源交易网",
    "url": "https://www.cqggzy.com",
    "source_level": "地方省市",
    "province": "重庆",
    "city": "重庆",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "重庆全市公共资源交易项目"
  },
  {
    "name": "重庆市政府采购网",
    "url": "https://www.ccgp-chongqing.gov.cn",
    "source_level": "地方省市",
    "province": "重庆",
    "city": "重庆",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "重庆全市政府采购项目"
  },
  {
    "name": "陕西政府采购网",
    "url": "http://www.ccgp-shaanxi.gov.cn",
    "source_level": "地方省市",
    "province": "陕西",
    "city": "西安",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "陕西全省政府采购项目"
  },
  {
    "name": "陕西省公共资源交易中心",
    "url": "http://www.sxggzyjy.cn",
    "source_level": "地方省市",
    "province": "陕西",
    "city": "西安",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "陕西全省公共资源交易项目"
  },
  {
    "name": "青海省公共资源交易网",
    "url": "https://www.qhggzyjy.gov.cn",
    "source_level": "地方省市",
    "province": "青海",
    "city": "西宁",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "青海全省公共资源交易项目"
  },
  {
    "name": "青海省政府采购网",
    "url": "http://www.ccgp-qinghai.gov.cn",
    "source_level": "地方省市",
    "province": "青海",
    "city": "西宁",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "青海全省政府采购项目"
  },
  {
    "name": "黑龙江省公共资源交易网",
    "url": "https://ggzyjyw.hlj.gov.cn",
    "source_level": "地方省市",
    "province": "黑龙江",
    "city": "哈尔滨",
    "platform_type": "公共资源交易",
    "is_official": 1,
    "enabled": 1,
    "notes": "黑龙江全省招投标项目"
  },
  {
    "name": "黑龙江省政府采购网",
    "url": "https://hljcg.hlj.gov.cn",
    "source_level": "地方省市",
    "province": "黑龙江",
    "city": "哈尔滨",
    "platform_type": "政府采购",
    "is_official": 1,
    "enabled": 1,
    "notes": "黑龙江全省政府采购项目"
  },
  {
    "name": "上海阳光医药采购网",
    "url": "https://www.smpaa.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "医药 / 医疗行业招标采购（上海区域）"
  },
  {
    "name": "中国交建物资采购管理信息系统",
    "url": "https://ec.ccccltd.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "建筑 / 基建",
    "is_official": 1,
    "enabled": 1
  },
  {
    "name": "中国医疗器械采购公共服务平台",
    "url": "https://www.yixue360.com",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "医药 / 医疗行业招标采购（全国）"
  },
  {
    "name": "中国电信阳光采购网",
    "url": "https://caigou.chinatelecom.com.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "通信 / IT 行业招标采购（电信项目）"
  },
  {
    "name": "中国电力招标网",
    "url": "https://www.ebnew.com",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "电力 / 能源",
    "is_official": 1,
    "enabled": 1
  },
  {
    "name": "中国移动采购与招标网",
    "url": "https://b2b.10086.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "通信 / IT 行业招标采购（移动项目）"
  },
  {
    "name": "中国联通采购与招标网",
    "url": "https://www.cuecp.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "通信 / IT 行业招标采购（联通项目）"
  },
  {
    "name": "中国铁路采购与物流平台",
    "url": "https://wz.95306.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "其他行业",
    "is_official": 1,
    "enabled": 1
  },
  {
    "name": "中铁鲁班商务网",
    "url": "https://luban.crec.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "建筑 / 基建行业招标采购（中铁项目）"
  },
  {
    "name": "云筑网（中建）",
    "url": "https://www.yzw.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "建筑 / 基建行业招标采购（中建项目）"
  },
  {
    "name": "南方电网供应链统一服务平台",
    "url": "https://www.bidding.csg.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "电力行业招标采购（南方电网项目）"
  },
  {
    "name": "国家电网电子商务平台",
    "url": "https://ecp.sgcc.com.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "电力行业招标采购（国家电网项目）"
  },
  {
    "name": "国家能源集团电子商务平台",
    "url": "https://www.chnenergybidding.com.cn",
    "source_level": "行业垂直",
    "province": "全国",
    "city": "全国",
    "platform_type": "行业核心",
    "is_official": 1,
    "enabled": 1,
    "notes": "能源行业招标采购（国能集团项目）"
  },
  {
    "name": "乙方宝",
    "url": "https://www.yifangbao.com",
    "source_level": "第三方综合",
    "province": "全国",
    "city": "全国",
    "platform_type": "聚合平台",
    "is_official": 0,
    "enabled": 1
  },
  {
    "name": "千里马招标网",
    "url": "https://www.qianlima.com",
    "source_level": "第三方综合",
    "province": "全国",
    "city": "全国",
    "platform_type": "聚合平台",
    "is_official": 0,
    "enabled": 1
  },
  {
    "name": "招标采购导航网",
    "url": "https://www.chinabidding.cn",
    "source_level": "第三方综合",
    "province": "全国",
    "city": "全国",
    "platform_type": "聚合平台",
    "is_official": 0,
    "enabled": 1
  },
  {
    "name": "招标雷达",
    "url": "https://www.bidradar.com",
    "source_level": "第三方综合",
    "province": "全国",
    "city": "全国",
    "platform_type": "聚合平台",
    "is_official": 0,
    "enabled": 1
  },
  {
    "name": "比地招标网",
    "url": "https://www.bidizhaobiao.com",
    "source_level": "第三方综合",
    "province": "全国",
    "city": "全国",
    "platform_type": "聚合平台",
    "is_official": 0,
    "enabled": 1
  }
];

module.exports = biddingSites;
