// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/maylis/Desktop/github上的项目/项目评估系统/PPA/frontend/ppa_frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/Users/maylis/Desktop/github上的项目/项目评估系统/PPA/frontend/ppa_frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FormOutlined';
import BoxPlotOutlined from '/Users/maylis/Desktop/github上的项目/项目评估系统/PPA/frontend/ppa_frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BoxPlotOutlined';
import SettingOutlined from '/Users/maylis/Desktop/github上的项目/项目评估系统/PPA/frontend/ppa_frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import RobotOutlined from '/Users/maylis/Desktop/github上的项目/项目评估系统/PPA/frontend/ppa_frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RobotOutlined';
import GlobalOutlined from '/Users/maylis/Desktop/github上的项目/项目评估系统/PPA/frontend/ppa_frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/GlobalOutlined';
import MonitorOutlined from '/Users/maylis/Desktop/github上的项目/项目评估系统/PPA/frontend/ppa_frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MonitorOutlined';
export default { DashboardOutlined, FormOutlined, BoxPlotOutlined, SettingOutlined, RobotOutlined, GlobalOutlined, MonitorOutlined };
