const endpoints = [
  { method: 'GET', path: '/api/health', group: 'health', priority: 'P0', mode: 'included' },

  { method: 'GET', path: '/api/config/roles', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'POST', path: '/api/config/roles', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'PUT', path: '/api/config/roles/:id', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'DELETE', path: '/api/config/roles/:id', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'GET', path: '/api/config/risk-items', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'POST', path: '/api/config/risk-items', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'PUT', path: '/api/config/risk-items/:id', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'DELETE', path: '/api/config/risk-items/:id', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'GET', path: '/api/config/travel-costs', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'POST', path: '/api/config/travel-costs', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'PUT', path: '/api/config/travel-costs/:id', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'DELETE', path: '/api/config/travel-costs/:id', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'GET', path: '/api/config/business-pricing', group: 'config', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/config/business-pricing', group: 'config', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/config/all', group: 'config', priority: 'P0', mode: 'included' },
  { method: 'GET', path: '/api/config/ai-models', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/config/ai-models/current', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/config/ai-models/current-vision', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/config/ai-models/:id', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/config/ai-models', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/config/ai-models/:id', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/config/ai-models/:id', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/config/ai-models/:id/set-current', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/config/ai-models/:id/set-current-vision', group: 'config-ai', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/config/ai-models/:id/test', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI provider call' },
  { method: 'POST', path: '/api/config/ai-models/test-temp', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI provider call' },
  { method: 'GET', path: '/api/config/prompts', group: 'prompts', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/config/prompts/:id', group: 'prompts', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/config/prompts', group: 'prompts', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/config/prompts/:id', group: 'prompts', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/config/prompts/:id', group: 'prompts', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/config/prompts/:id/copy', group: 'prompts', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/config/prompts/:id/preview', group: 'prompts', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/config/prompt-module-tags', group: 'prompts', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/config/prompt-module-tags', group: 'prompts', priority: 'P2', mode: 'included' },
  { method: 'PUT', path: '/api/config/prompt-module-tags/:id', group: 'prompts', priority: 'P2', mode: 'included' },
  { method: 'DELETE', path: '/api/config/prompt-module-tags/:id', group: 'prompts', priority: 'P2', mode: 'included' },

  { method: 'POST', path: '/api/calculate', group: 'calculation', priority: 'P0', mode: 'included' },

  { method: 'GET', path: '/api/projects', group: 'projects', priority: 'P0', mode: 'included' },
  { method: 'POST', path: '/api/projects', group: 'projects', priority: 'P0', mode: 'included' },
  { method: 'GET', path: '/api/projects/templates', group: 'projects', priority: 'P0', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id', group: 'projects', priority: 'P0', mode: 'included' },
  { method: 'PUT', path: '/api/projects/:id', group: 'projects', priority: 'P0', mode: 'included' },
  { method: 'DELETE', path: '/api/projects/:id', group: 'projects', priority: 'P0', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id/export/pdf', group: 'projects', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id/export/excel', group: 'projects', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id/business-quote', group: 'projects', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/projects/:id/business-quote', group: 'projects', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/projects/:id/attachments/upload', group: 'projects-files', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id/attachments', group: 'projects-files', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id/attachments/download/:filename', group: 'projects-files', priority: 'P2', mode: 'included' },
  { method: 'DELETE', path: '/api/projects/:id/attachments/:filename', group: 'projects-files', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id/attachments/check', group: 'projects-files', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/projects/:id/push/validate', group: 'projects-push', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/projects/:id/push', group: 'projects-push', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/projects/:id/push-history', group: 'projects-push', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/templates', group: 'projects', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/templates', group: 'projects', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/templates/templates', group: 'projects', priority: 'P1', mode: 'included' },

  { method: 'GET', path: '/api/dashboard/overview', group: 'dashboard', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/dashboard/trend', group: 'dashboard', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/dashboard/cost-range', group: 'dashboard', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/dashboard/keywords', group: 'dashboard', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/dashboard/dna', group: 'dashboard', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/dashboard/top-roles', group: 'dashboard', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/dashboard/top-risks', group: 'dashboard', priority: 'P1', mode: 'included' },

  { method: 'GET', path: '/api/ai/prompts', group: 'ai-readonly', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/ai/module-prompts', group: 'ai-readonly', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/ai/workload-prompts', group: 'ai-readonly', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/ai/project-tag-prompts', group: 'ai-readonly', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/ai/assess-risk', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI provider call' },
  { method: 'POST', path: '/api/ai/normalize-risk-names', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI provider call' },
  { method: 'POST', path: '/api/ai/analyze-project-modules', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI provider call' },
  { method: 'POST', path: '/api/ai/evaluate-workload', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI provider call' },
  { method: 'POST', path: '/api/ai/generate-project-tags', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI provider call' },

  { method: 'GET', path: '/api/web3d/config/risk-items', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/web3d/config/risk-items', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/web3d/config/risk-items/:id', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/web3d/config/risk-items/:id', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/web3d/config/workload-templates', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/web3d/config/workload-templates', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/web3d/config/workload-templates/:id', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/web3d/config/workload-templates/:id', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/web3d/ai/step4-prompts', group: 'web3d', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/web3d/ai/step4-analyze', group: 'external-ai', priority: 'P2', mode: 'skipped', reason: 'external AI vision analysis call' },
  { method: 'POST', path: '/api/web3d/projects/calculate', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/web3d/projects/:id/calculate', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/web3d/projects/:id/export', group: 'web3d', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/web3d/projects/:id', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/web3d/projects', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/web3d/projects', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/web3d/projects/:id', group: 'web3d', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/web3d/projects/:id', group: 'web3d', priority: 'P1', mode: 'included' },

  { method: 'GET', path: '/api/monitoring/logs', group: 'monitoring', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/monitoring/stats', group: 'monitoring', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/monitoring/logs/:requestHash', group: 'monitoring', priority: 'P3', mode: 'included' },
  { method: 'GET', path: '/api/contracts/files', group: 'contracts', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/contracts/file', group: 'contracts', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/contracts/recommend', group: 'contracts', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/wiki', group: 'wiki', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/wiki/content', group: 'wiki', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/wiki/relations', group: 'wiki', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/wiki/relations', group: 'wiki', priority: 'P2', mode: 'included' },

  { method: 'GET', path: '/api/opportunity/bidding-sites', group: 'opportunity', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/opportunity/bidding-sites/:id', group: 'opportunity', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/opportunity/bidding-sites', group: 'opportunity', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/opportunity/bidding-sites/:id', group: 'opportunity', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/opportunity/bidding-sites/:id', group: 'opportunity', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/opportunity/bidding-sites/:id/script', group: 'opportunity', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/opportunity/bidding-sites/:id/validate', group: 'external-network', priority: 'P2', mode: 'skipped', reason: 'external website validation call' },
  { method: 'GET', path: '/api/opportunity/tender-staging', group: 'opportunity', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/opportunity/tender-staging/sync', group: 'opportunity-files', priority: 'P3', mode: 'skipped', reason: 'local source-file ingestion; covered by specialized file tests' },
  { method: 'POST', path: '/api/opportunity/tender-staging/:id/push', group: 'opportunity', priority: 'P3', mode: 'skipped', reason: 'requires staged tender fixture and downstream PPA project creation' },

  { method: 'GET', path: '/api/form-design/stats', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/form-design/validate/field', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/form-design/validate/form/:formId', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/form-design/projects', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/form-design/projects/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/form-design/projects', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/form-design/projects/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/form-design/projects/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/form-design/projects/:projectId/apps', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/form-design/apps', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/form-design/apps/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/form-design/apps/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/form-design/apps/:appId/forms', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/form-design/forms', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/form-design/forms/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/form-design/forms/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/form-design/forms/:formId/fields', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/form-design/fields', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/form-design/fields/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/form-design/fields/:id', group: 'form-design', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/form-design/fields/batch', group: 'form-design', priority: 'P2', mode: 'included' },

  { method: 'GET', path: '/api/data-metrics/projects', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/projects/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/data-metrics/projects', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/data-metrics/projects/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/data-metrics/projects/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/stats', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/filter-options', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/linked-projects', group: 'data-metrics', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/data-metrics', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/data-metrics/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/data-metrics/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/data-metrics/batch', group: 'data-metrics', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/data-metrics/import/preview', group: 'data-metrics-file', priority: 'P2', mode: 'skipped', reason: 'xlsx fixture covered by specialized file import tests' },
  { method: 'POST', path: '/api/data-metrics/import', group: 'data-metrics-file', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/export', group: 'data-metrics-file', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/categories/tree', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'POST', path: '/api/data-metrics/categories', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'PUT', path: '/api/data-metrics/categories/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'DELETE', path: '/api/data-metrics/categories/:id', group: 'data-metrics', priority: 'P1', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/projects/:id/agent-context', group: 'data-metrics-agent', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/projects/:id/agent-layout', group: 'data-metrics-agent', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/data-metrics/projects/:id/agent-feedback', group: 'data-metrics-agent', priority: 'P2', mode: 'included' },
  { method: 'POST', path: '/api/data-metrics/projects/:id/convert-to-ppa-template', group: 'data-metrics-agent', priority: 'P2', mode: 'included' },
  { method: 'GET', path: '/api/data-metrics/projects/:id/export/json', group: 'data-metrics-agent', priority: 'P2', mode: 'included' },
];

module.exports = { endpoints };
