// 常量定义

// 默认值
const DEFAULTS = {
  TRAVEL_COST_PER_MONTH: 10800, // 元/人/月
  MAINTENANCE_DAILY_COST: 1600, // 元/人/天
  WORK_DAYS_PER_MONTH: 21.5, // 每月工作天数
  AVERAGE_UNIT_PRICE: 0.16 // 平均单价（万元）
};

const RISK = {
  DEFAULT_MAX_SCORE: 100,
  BASE_THRESHOLD_RATIO: 0.7,
  MID_THRESHOLD_RATIO: 1.0,
  PEAK_THRESHOLD_RATIO: 1.2,
  MID_FACTOR: 1.2,
  FACTOR_CAP: 1.5,
  LEVEL_THRESHOLDS: {
    LOW: 0.4,
    HIGH: 0.7
  }
};

module.exports = {
  DEFAULTS,
  RISK
};
